 const types = {
    NO_EMAIL:"NO_EMAIL",
  NOT_EMAIL:"NOT_EMAIL",
  NO_PASSWORD:"NO_PASSWORD",
  NOT_PASSWORD_LENGTH:"NOT_PASSWORD_LENGTH",
  DO_NOT_MATCH:"DO_NOT_MATCH",
  MAIL_SENT:"MAIL_SENT",
  PASS_CHANGED:"PASS_CHANGED",
  MAIL_EXIST:"MAIL_EXIST",
  REGISTERED:"REGISTERED",
  INVALID_LOG_PASS: "INVALID_LOG_PASS",
  MAIL_NOT_EXIST:"MAIL_NOT_EXIST"
}

module.exports = types